# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeofenceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeofenceApp

  target 'GeofenceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeofenceAppUITests' do
    # Pods for testing
  end

  pod 'Firebase/Crashlytics'

end
